### ISSUE TITLE
Could not find method estilo() for arguments...

### ISSUE THREAD

**Issue by wheelerlaw** [anshulverma/gradle-estilo-plugin#2]
I've got this at the top of my `build.gradle`:
```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'net.anshulverma.gradle:gradle-estilo-plugin:0.4.8'
    }
}
apply plugin: 'net.anshulverma.gradle.estilo'
```
I used the sample in this project's readme. But I keep getting:

```
Could not find method estilo() for arguments [build_jedtzp9goevtjg338jv00b9p$_run_closure3@2b27b1c9] on root project 'snickers' of type org.gradle.api.Project.
```

**Comment by wheelerlaw** [comment]
Nevermind. I took a look at the plugin source and saw: `if (project.plugins.hasPlugin('java')) {`, and realized I had applied the plugin before I apply the `application` plugin.

**Comment by anshulverma** [comment]
Thanks for following up. Hopefully it works smoothly now

**Comment by christophercolumbusdog** [comment]
Any way of getting help with the same issue? I'm attempting to use estilo on an Android Gradle app, but I'm getting the same error. I have the following module gradle file:

`apply plugin: 'com.android.application'
apply plugin: 'net.anshulverma.gradle.estilo'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.mac.chartr"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    testImplementation "org.robolectric:robolectric:3.7.1"
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'com.android.support:support-v4:27.1.0'
    implementation 'com.google.android.gms:play-services-maps:11.8.0'
    implementation 'com.google.android.gms:play-services-places:11.8.0'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:support-annotations:27.1.0'

    compile 'com.android.support:appcompat-v7:27.1.0'
    compile 'com.android.support:design:27.1.0'
    compile 'com.github.ittianyu:BottomNavigationViewEx:1.2.4'
    compile "com.android.support:design:27.1.0"
    compile 'com.android.support:cardview-v7:27.1.0'
    compile 'com.android.support:recyclerview-v7:27.1.0'
    compile 'com.github.bumptech.glide:glide:4.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'
    compile 'de.hdodenhof:circleimageview:2.2.0'
    compile 'com.miguelcatalan:materialsearchview:1.4.0'
    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.6.15'


    testCompile "org.mockito:mockito-core:2.8.9"
    testCompile "org.robolectric:shadows-support-v4:3.3.2"
    testCompile group: 'org.powermock', name: 'powermock-api-mockito2', version: '1.7.3'
    testCompile group: 'org.powermock', name: 'powermock-module-junit4', version: '1.7.3'
    androidTestCompile 'org.mockito:mockito-android:2.7.22'
    testCompile 'junit:junit:4.12'
    testCompile 'commons-logging:commons-logging:1.1.1'

    androidTestCompile 'com.android.support.test.espresso:espresso-core:3.0.1'
    androidTestCompile 'com.android.support.test:runner:1.0.1'

    compile 'com.android.volley:volley:1.0.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.google.code.gson:gson:2.8.0'
}

estilo {
    source 'google' // starting point for checkstyle checks (other option: 'sun')

    ignoreWarnings false // ignore checkstyle warning and let the build continue

    toolVersion '6.12.1' // set version of checkstyle to use

    // add checkstyle suppressions.
    // this automatically adds a 'SuppressionFilter' to checkstyle.xml
    suppressions {
        suffix('Test.java') {
            checks 'LineLength'
        }
    }

    // setup header check.
    // this automatically adds a 'RegexpHeader' check to checkstyle.xml.
    header regexp: true, multiLines: [7, 8, 9, 10, 12], template: '''^/\\*\\*
^ \\* Copyright © 2015 Anshul Verma. All Rights Reserved.
^ \\*/
^\$
^package
^\$
^import
^\$
^import static
^\$
^/\\*\\*
^ \\*((?! @author )|\$)
^ \\* @author anshul\\.verma86@gmail\\.com \\(Anshul Verma\\)
^ \\*/
'''
}`

With the following Project build file:

`buildscript {
    
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'net.anshulverma.gradle:gradle-estilo-plugin:0.4.8'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

I've tried moving the buildscript into the module build.gradle, I've made sure to put the "apply plugin" after the "application" plugin.... I just don't know what could be going on.
